---
include:
  - "app/**/*.rb"
  - "config/**/*.rb"
  - "lib/**/*.rb"
  - "app/models/**/*.rb"
  - "app/controllers/**/*.rb"
  - "app/helpers/**/*.rb"
  - "app/jobs/**/*.rb"
  - "app/mailers/**/*.rb"
  - "app/services/**/*.rb"
  - "app/views/**/*.rb"
exclude:
  - "vendor/**"
  - "tmp/**"
  - "log/**"
require: []
domains: []
reporters:
  - rubocop
  - require_not_found
require_paths:
  - "app"
  - "lib"
  - "config"
max_files: 5000
