# Generated by Django 4.1.5 on 2023-01-27 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemuser',
            old_name='firt_name',
            new_name='first_name',
        ),
    ]
